class MyUtils {
  static List<String> getPlaceNames() => [
        "Tashkent",
        "Andijan",
        "Olmazor",
        "London",
        "Asaka",
        "Chust",
        "Samarkand",
        "Bukhara",
        "Moscow",
        "Afghanistan",
        "Albania",
        "Bahrain",
        "Barbados",
        "Cameroon",
        "Cuba",
        "Germany",
        "India",
        "Iraq",
        "Italy",
        "Japan",
        "Latvia",
        "Malaysia",
        "Maldives",
        "New Zealand",
        "North Korea",
        "Qatar",
        "Serbia",
        "Turkey",
        "Zambia",
        "Monaco",
        "Iran",
        "Egypt",
        "Canada",
      ];
}
